language: python
python:
- '3.6'
dist: trusty
install:
- bash devtools/install.sh
- export PATH="$HOME/anaconda/bin:$PATH"
- source activate call_schedule
script:
- echo $PATH
- which jupyter
- bash devtools/tests/test.sh
